### ISSUE TITLE
adding FAQ to the website

### ISSUE THREAD

**Issue by saifikhan** [rustox/rep#1]
we need to add an FAQ section to rustox website https://sites.google.com/view/rustox

some questions are

- what is the venue of the event
- what is the goal of the community
- how often to do you conduct the event
- is the event 'free of charge' or a 'paid event'
- do you have a code of conduct for the event
- do we get help on how to setup rust/cargo etc
- my company wants to conduct rustox event at its office, how do you liason

we could evolve the list further.

**Comment by raginijx** [comment]
The last section of the Home page is Legal section.
So, What makes more sense:
  * To add FAQ section on the same page ?
    OR
  * To add new page and add rest of the sections to the new page ?

**Comment by saifikhan** [comment]
we start with a couple of questions, and in due course there are going to be many more. 

as a result the first page will become rather long.

how about adding a **new** page for 'FAQ' ?

**Comment by raginijx** [comment]
Yes. It makes sense to add a new page to the website. 
Will do that.

**Comment by raginijx** [comment]
Added the FAQ page on the website.
