### ISSUE TITLE
attendance sheet required

### ISSUE THREAD

**Issue by raginijx** [rustox/rep#10]
We need to have an attendance sheet for the meetup event.

This is also a requirement by the venue sponsors.

**Comment by saifikhan** [comment]
Attendance sheet for Rust Bangalore (rustox) community meetup is ready.

The PDF version can be accessed / downloaded from this link
https://drive.google.com/drive/folders/0ByfXiRSzT2CxRE1xenhCYUxuS00?usp=sharing
