### ISSUE TITLE
adding code of conduct

### ISSUE THREAD

**Issue by raginijx** [rustox/rep#3]
As an open community, we welcome diversity.

Keeping the diversity of the community in mind, A section for code of conduct needs to be added.

**Comment by saifikhan** [comment]
Can you add a code of conduct ?

**Comment by raginijx** [comment]
Yes I will do that.

**Comment by saifikhan** [comment]
reviewed the code of conduct at https://sites.google.com/view/rustox/code-of-conduct

Looks good to me.
