### ISSUE TITLE
information to share with venue sponsor

### ISSUE THREAD

**Issue by saifikhan** [rustox/rep#6]
for _hosting_ the community event, we need a **venue** _sponsor_.

perhaps the following information may help the sponsor, decide one way or the other

- 'rustox' meetup is a "technology" focussed community event
- follows a code of conduct
- frequency is once a month
- on a saturday afternoon
- timings would be 1500 - 1800 hrs
- 20 - 25 people are expected
- will have a attendance sheet (records name and contact details)

what the sponsor **should** provide

- meeting room
- LCD projector
- white board
- chairs (for 20 - 25 people)
- access to washroom and drinking water

what is **outside** the scope of sponsorship (we don't need)
- refreshments
- any other expense item

**Comment by raginijx** [comment]
Should we fix one Saturday for every month ?
For example: second Saturday of the month for the community event.

**Comment by saifikhan** [comment]
How about the "third" saturday of every month ?

The 'second' saturday is already quite crowded.

Additionally, i believe once Jeeva get's back to us, we can further align initiatives together with 'Open Source' and 'Jenkins Area meetup'.

**Comment by raginijx** [comment]
venue confirmed with Siddartha, 91Springboard.

If they have any event on the third Saturday, they will notify us one week in advance.
