### ISSUE TITLE
meetup subscription sponsor

### ISSUE THREAD

**Issue by saifikhan** [rustox/rep#7]
to reach out to the potential community and engage the Rust Bangalore community better, it may help to have a presence on meetup.com

the unlimited subscription costs about USD 60 annually or about 60 x 70 =  INR 4,200.

it would help, if we could raise funds for meetup account or have a subscription sponsor.

What does everyone think ?

**Comment by raginijx** [comment]
I think it's good idea of having presence on meetup.com

**Comment by raginijx** [comment]
The most painful part of cloud services is "vendor lock-in".

So, consider Meetup.com as the same.

Let's not have a meetup page.

We can push the rustox website, through other mediums (including meetup.com on the other community pages)

As the community is free and open, there should be no lock-ins, in any form.

**Comment by saifikhan** [comment]
Yes, as a FOSS community, we should avoid vendor lock-in.
